"""FastAPI entrypoint for Maatru. Phase 3 thin slice: TTS + check_recognition + healthz.

No Gemma 4 calls in kid-loop endpoints per the planner-bundling architecture
(decisions.md 2026-05-10). Feedback strings are hardcoded for Phase 3; the
planner will populate per-step FeedbackVariants in Phase 5.5.
"""
import random
from pathlib import Path
from typing import Literal

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, Response
from pydantic import BaseModel, Field

from app.tts import synthesize

_REPO_ROOT = Path(__file__).resolve().parent.parent
_STATIC_DIR = _REPO_ROOT / "static"
_KID_HTML = _STATIC_DIR / "kid.html"

# Phase 3 hardcoded feedback pool. Replaced in Phase 5.5 by per-step
# FeedbackVariants generated by the planner's single agentic call.
_PHASE3_POSITIVE: list[str] = ["Yes! That's అ", "Great!", "Perfect!"]
_PHASE3_RETRY: list[str] = [
    "Try again — listen carefully",
    "Not quite — listen for the sound",
]


class PronounceRequest(BaseModel):
    character: str = Field(..., min_length=1, description="Character to pronounce.")
    language: Literal["te", "hi"] = Field(default="te", description="ISO-639-1 language code.")


class CheckRequest(BaseModel):
    target: str = Field(..., min_length=1)
    chosen: str = Field(..., min_length=1)


class CheckResponse(BaseModel):
    correct: bool
    feedback: str


app = FastAPI(title="Maatru", version="0.1.0")


@app.get("/healthz")
async def healthz() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/")
async def kid_root() -> FileResponse:
    if not _KID_HTML.is_file():
        raise HTTPException(status_code=500, detail="kid.html missing")
    return FileResponse(_KID_HTML, media_type="text/html")


@app.post("/api/pronounce")
async def api_pronounce(req: PronounceRequest) -> Response:
    try:
        audio = await synthesize(req.character, language=req.language)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=f"TTS failure: {e}") from e
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    return Response(content=audio, media_type="audio/mpeg")


@app.post("/api/check_recognition", response_model=CheckResponse)
async def api_check_recognition(req: CheckRequest) -> CheckResponse:
    correct = req.target == req.chosen
    pool = _PHASE3_POSITIVE if correct else _PHASE3_RETRY
    return CheckResponse(correct=correct, feedback=random.choice(pool))
